########## nebula-storaged-listener ###########
########## basics ##########
--daemonize=true
--pid_file=pids/nebula-storaged-listener.pid
--local_config=true

########## logging ##########
--log_dir=logs_storaged_listener
--minloglevel=0
--v=0
--logbufsecs=0
--redirect_stdout=true
--stdout_log_file=storaged-listener-stdout.log
--stderr_log_file=storaged-listener-stderr.log
--stderrthreshold=3
--timestamp_in_logfile_name=true

########## networking ##########
--meta_server_addrs=127.0.0.1:9559,127.0.0.1:9561,127.0.0.1:9563
--local_ip=127.0.0.1
--port=9789

--ws_ip=0.0.0.0
--ws_http_port=19789
--heartbeat_interval_secs=10

########## kafka ##########
--kafka_brokers=127.0.0.1:9092
--kafka_topic_prefix=nebula
--kafka_security_protocol=PLAINTEXT

########## storage ##########
--listener_path=data/listener
--data_path=data
--part_man_type=memory
--rocksdb_batch_size=4096
--rocksdb_block_cache=4
--engine_type=rocksdb
--part_type=simple
